
### Get all companies
GET http://localhost:3000/companies


### Get single company
GET http://localhost:3000/company/6652b33384b4949341f3da14



### Create a company
POST http://localhost:3000/company HTTP/1.1
content-type: application/json

{
    "name": "testCompany",
    "address": "Rexburg Idaho",
    "phone": "208-888-9101",
    "email": "Test@test.com"
}

### Update a company
PUT http://localhost:3000/company/6640434a6963a73879dc33de HTTP/1.1
Content-Type: application/json

{
    "name": "new testCompany",
    "address": "Idaho Falls",
    "phone": "208-777-8202",
    "email": "Test@test.com"
}

### Delete a company
DELETE http://localhost:3000/company/6640434a6963a73879dc33de



// Server Calls
### Get all companies
GET https://cse341-p2-p2cj.onrender.com/companies


### Get single company
GET https://cse341-p2-p2cj.onrender.com/company/66403cb753842981bbad3bda



### Create a company
POST https://cse341-p2-p2cj.onrender.com/company HTTP/1.1
content-type: application/json

{
    "name": "testCompany",
    "address": "Rexburg Idaho",
    "phone": "208-888-9101",
    "email": "Test@test.com"
}

### Update a company
PUT https://cse341-p2-p2cj.onrender.com/company/6640462abaf4f49f87c963da HTTP/1.1
Content-Type: application/json

{
    "name": "new testCompany",
    "address": "Idaho Falls",
    "phone": "208-777-8202",
    "email": "Test@test.com"
}

### Delete a company
DELETE https://cse341-p2-p2cj.onrender.com/company/6640462abaf4f49f87c963da